baseURL = "https://quiettime.netlify.app/"
languageCode = "en-gb"
title = "Quiet time notes"
theme = "tale"

comments = true

# Metadata mostly used in document's head
description = "Quiet time notes"
themeColor = "#494f5c"

[taxonomies]
  books = "book"
  notes = "tags"

[params]
  author = "Taiwo Kareem"
  description = "Compilation of my quiet time from YouVersion Bible"
  css = ["custom.css"]


[menu]
  [[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 1

  [[menu.main]]
    name = "Books"
    url = "/book/"
    weight = 2

  [[menu.main]]
    name = "Songs"
    url = "/songs/"
    weight = 3

  [[menu.main]]
    name = "Song tags"
    url = "/tags/"
    weight = 4